// <auto-generated />
using System;
using ASACaseManagement.Services.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASACaseManagement.Services.Migrations
{
    [DbContext(typeof(CaseContext))]
    partial class CaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ASACaseManagement.Services.Entities.CaseFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("CaseFiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseNumber = "1001-001",
                            CreationDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description of disputes between a landlord and tenant goes here.",
                            Title = "Disputes between a landlord and tenant"
                        },
                        new
                        {
                            Id = 2,
                            CaseNumber = "2001-002",
                            CreationDate = new DateTime(2020, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description of committed homicide felony offense goes here.",
                            Title = "Committed homicide felony offense"
                        },
                        new
                        {
                            Id = 3,
                            CaseNumber = "3001-003",
                            CreationDate = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description of traffic rules violation goes here.",
                            Title = "Traffic rules violation"
                        });
                });

            modelBuilder.Entity("ASACaseManagement.Services.Entities.Respondent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("CaseFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CaseFileId");

                    b.ToTable("Respondents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Village: V1, Post Office: PO1, Thana: T1, District: D1, Division: Dv1, Bangladesh",
                            CaseFileId = 1,
                            DateOfBirth = new DateTime(1988, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Shafiq",
                            LastName = "Anwar"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Village: V2, Post Office: PO2, Thana: T2, District: D2, Division: Dv2, Bangladesh",
                            CaseFileId = 1,
                            DateOfBirth = new DateTime(1984, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mohammad",
                            LastName = "Hasan"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Village: V3, Post Office: PO3, Thana: T3, District: D3, Division: Dv3, Bangladesh",
                            CaseFileId = 2,
                            DateOfBirth = new DateTime(1988, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ahmed",
                            LastName = "Arefin"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Village: V4, Post Office: PO4, Thana: T4, District: D4, Division: Dv4, Bangladesh",
                            CaseFileId = 2,
                            DateOfBirth = new DateTime(1988, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bilkis",
                            LastName = "Banu"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Village: V5, Post Office: PO5, Thana: T5, District: D5, Division: Dv5, Bangladesh",
                            CaseFileId = 3,
                            DateOfBirth = new DateTime(1996, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zebunnesa",
                            LastName = "Begum"
                        });
                });

            modelBuilder.Entity("ASACaseManagement.Services.Entities.Respondent", b =>
                {
                    b.HasOne("ASACaseManagement.Services.Entities.CaseFile", "CaseFile")
                        .WithMany("Respondents")
                        .HasForeignKey("CaseFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
